### ISSUE TITLE
TypeError when using helper-markdown with Handlebars

### ISSUE THREAD

**Issue by almeidap** [helpers/helper-markdown#1]
When registering `helper-markdown` with Handlebars:

``` javascript
module.exports.register = function (handlebars) {
    handlebars.registerHelper('markdown', require('helper-markdown'));
};
```

...the following exception is thrown:

```
[...]\node_modules\mixin-deep\index.js:30
    this[key] = val;
              ^
TypeError: Cannot set property parent of [object Object] which has only a getter
    at Buffer.copy ([...]\node_modules\mixin-deep\index.js:30:15)
    at forIn ([...]\node_modules\for-in\index.js:12:12)
    at mixinDeep ([...]\node_modules\mixin-deep\index.js:11:7)
    at File.copy ([...]\node_modules\mixin-deep\index.js:28:5)
    at forIn ([...]\node_modules\for-in\index.js:12:12)
    at mixinDeep ([...]\node_modules\mixin-deep\index.js:11:7)
    at Object.copy ([...]\node_modules\mixin-deep\index.js:28:5)
    ...
```

This looks to be the faulty source code line:

``` javascript
options = merge({ html: true, breaks: true }, config, options);
```

(cf. https://github.com/helpers/helper-markdown/blob/fa6f8578741c61f4affd0ac3a9926ca1a919abc8/index.js#L36)

Commenting L36 fixes the exception and `helper-markdown` works then as expected.

**Comment by jonschlinkert** [comment]
closing since I believe this was resolved when the helper was refactored.
